export const NOTIFICATION_TYPES = {
  BOOKING_REQUEST: "BOOKING_REQUEST",
  BOOKING_APPROVED: "BOOKING_APPROVED",
  PROPERTY_SUBMITTED: "PROPERTY_SUBMITTED",
  PROPERTY_APPROVED: "PROPERTY_APPROVED",
} as const;

export const NOTIFICATION_TYPE_LABELS = {
  [NOTIFICATION_TYPES.BOOKING_REQUEST]: "Booking request",
  [NOTIFICATION_TYPES.BOOKING_APPROVED]: "Booking approved",
  [NOTIFICATION_TYPES.PROPERTY_SUBMITTED]: "Property submitted",
  [NOTIFICATION_TYPES.PROPERTY_APPROVED]: "Property approved",
} as const;
